# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-06 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='has_processed',
            field=models.CharField(choices=[('yes', '已处理'), ('no', '未处理')], default='no', max_length=4),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default='', max_length=48, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='contact',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='content',
            field=models.TextField(default='', verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='has_processed',
            field=models.CharField(choices=[('yes', '已处理'), ('no', '未处理')], default='no', max_length=4),
        ),
        migrations.AddField(
            model_name='feedback',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(default='', max_length=48, verbose_name='标题'),
        ),
    ]
