# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-27 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat_images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=48, verbose_name='标题')),
                ('image_url', models.CharField(max_length=256, verbose_name='链接地址')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cat', verbose_name='图片')),
                ('like_nums', models.IntegerField(default=0, verbose_name='点赞数')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('describe', models.CharField(blank=True, max_length=128, verbose_name='描述')),
                ('width', models.IntegerField(default=0, verbose_name='图片宽度')),
                ('height', models.IntegerField(default=0, verbose_name='图片高度')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='cat_image',
            name='author',
        ),
        migrations.DeleteModel(
            name='Cat_Image',
        ),
    ]
