# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-05 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_images', '0005_catimage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catimage',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('publish', '出版')], default='draft', max_length=8, verbose_name='状态'),
        ),
    ]
