# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-05 01:41
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cat_images', '0006_auto_20171005_0108'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='catimage',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
