# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-05 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat_images', '0007_auto_20171005_0141'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='catimage',
            managers=[
            ],
        ),
    ]
