# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-06 05:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat_images', '0008_auto_20171005_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='catimage',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL),
        ),
    ]
